"""initial_ai_operations_table

Revision ID: 6c2b3e6c0287
Revises: 3f1e7c33c26b
Create Date: 2026-08-17 21:46:30.978175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c2b3e6c0287'
down_revision: Union[str, Sequence[str], None] = '3f1e7c33c26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('capture_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_estimate_usd', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_operations_capture_id'), 'ai_operations', ['capture_id'], unique=False)
    op.create_index(op.f('ix_ai_operations_id'), 'ai_operations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_operations_user_id'), 'ai_operations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_operations_user_id'), table_name='ai_operations')
    op.drop_index(op.f('ix_ai_operations_id'), table_name='ai_operations')
    op.drop_index(op.f('ix_ai_operations_capture_id'), table_name='ai_operations')
    op.drop_table('ai_operations')
    # ### end Alembic commands ###
