"""Initial Captures Table

Revision ID: 3f1e7c33c26b
Revises: 45d8160e3927
Create Date: 2026-08-17 17:35:13.736487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f1e7c33c26b'
down_revision: Union[str, Sequence[str], None] = '45d8160e3927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_id'), 'captures', ['id'], unique=False)
    op.create_index(op.f('ix_captures_user_id'), 'captures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captures_user_id'), table_name='captures')
    op.drop_index(op.f('ix_captures_id'), table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
